name: atmos_gc_storage_fs
description: Analogs for Google Cloud Storage but in file system writed with pure dart
version: 0.1.0
homepage: https://github.com/Atom735/atmos_gc_storage/tree/master/atmos_gc_storage_fs

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  gcloud: ^0.8.5
  logging: ^1.0.2
  meta: ^1.7.0
  path: ^1.8.1

dev_dependencies:
  atmos_lints: ^0.16.1
